version: '3.7'

services:
  mongo-booking:
   image: mongo
   container_name: mongo_db
   ports: 
    - "27017:27017"

  api:
    container_name: booking
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - mongo-booking  